### ISSUE TITLE
Some emojis do not work

### ISSUE THREAD

**Issue by chriswill0w** [xoudini/emojica#5]
Some of the emojis which can be found here https://getemoji.com in the section "New 2017 Emojis released in June 2017" are not detected at all or are detected as "two emojis" (face plus modifier).
furthermore a lot of the people emojis with skin color modifier are detected incorrectly and rendered as two emojis (face plus modifier).
How can I fix this?
btw why are some huge blocks commented out in the Unicode.swift file?

I am using twemoji image files as they are supplied in the twemoji repo. I did not change the file names.
Tested with iOS 11.

**Comment by xoudini** [comment]
Yes, admittedly the Unicode 10 standard hasn't been implemented into the framework as of now, but I'll make sure to do that as soon as possible (give it a week or so). I'll also look into Emoji 5.0 specifics at the same time.

As for the 'huge blocks' commented out in the `Unicode.swift` file: the code points present in the ignored code are accounted for in other methods. The commented blocks are somewhat _specialised_ and aren't really essential to the functionality of the framework, you can read a more detailed description at line 1262 onwards in the same file.

**Comment by chriswill0w** [comment]
sound great, thanks!
do you have any idea why all the emojis with the skin and gender modifiers (should have been included already before Unicode 10, right?) do not seem to work? can you confirm that?

**Comment by xoudini** [comment]
@ltblueberry0 I'll have to look into it, so give me a day or two to investigate. If you could give me specific code points at which the conversion fails, that would be very helpful.

**Comment by chriswill0w** [comment]
most of these emojis are not working (same for other skin tones):

```
let emojica = Emojica()
somelabel.attributedText = emojica.convert(string: " 👱🏾‍♀️ 👱🏾 👴🏾 👵🏾 👲🏾 👳🏾‍♀️ 👳🏾 👮🏾‍♀️ 👮🏾 👷🏾‍♀️ 👷🏾 💂🏾‍♀️ 💂🏾 🕵🏾‍♀️ 🕵🏾 👩🏾‍⚕️ 👨🏾‍⚕️ 👩🏾‍🌾 👨🏾‍🌾 👩🏾‍🍳 👨🏾‍🍳 👩🏾‍🎓 👨🏾‍🎓 👩🏾‍🎤 👨🏾‍🎤 👩🏾‍🏫 👨🏾‍🏫 👩🏾‍🏭 👨🏾‍🏭 👩🏾‍💻 👨🏾‍💻 👩🏾‍💼 👨🏾‍💼 👩🏾‍🔧 👨🏾‍🔧 👩🏾‍🔬 👨🏾‍🔬 👩🏾‍🎨 👨🏾‍🎨 👩🏾‍🚒 👨🏾‍🚒 👩🏾‍✈️ 👨🏾‍✈️ 👩🏾‍🚀 👨🏾‍🚀 👩🏾‍⚖️ 👨🏾‍⚖️ 🤶🏾 🎅🏾 👸🏾 🤴🏾 👰🏾 🤵🏾 👼🏾 🤰🏾 🙇🏾‍♀️ 🙇🏾 💁🏾 💁🏾‍♂️ 🙅🏾 🙅🏾‍♂️ 🙆🏾 🙆🏾‍♂️ 🙋🏾 🙋🏾‍♂️ 🤦🏾‍♀️ 🤦🏾‍♂️ 🤷🏾‍♀️ 🤷🏾‍♂️ 🙎🏾 🙎🏾‍♂️ 🙍🏾 🙍🏾‍♂️ 💇🏾 💇🏾‍♂️ 💆🏾 💆🏾‍♂️ 🕴🏾 💃🏾 🕺🏾 🚶🏾‍♀️ 🚶🏾 🏃🏾‍♀️ 🏃🏾 🏋🏾‍♀️ 🏋🏾 🤸🏾‍♀️ 🤸🏾‍♂️ ⛹🏾‍♀️ ⛹🏾 🤾🏾‍♀️ 🤾🏾‍♂️ 🏌🏾‍♀️ 🏌🏾 🏄🏾‍♀️ 🏄🏾 🏊🏾‍♀️ 🏊🏾 🤽🏾‍♀️ 🤽🏾‍♂️ 🚣🏾‍♀️ 🚣🏾 🏇🏾 🚴🏾‍♀️ 🚴🏾 🚵🏾‍♀️ 🚵🏾 🤹🏾‍♀️ 🤹🏾‍♂️ 🛀🏾")
```

(scroll to the right ;-))

using unmodified icons from twemoji

**Comment by xoudini** [comment]
Thanks! I'll get back to you shortly.

**Comment by chriswill0w** [comment]
some more info: 
for this example 

```
let emojica = Emojica()
var test123 = emojica.convert(string: "👱🏾‍♀️👱🏾")
```
renders 4 images instead of two. it shows 3 images for the woman and one correct one for the man. 

events:
`private func replacement(for emoji: EmojiHandler) -> NSAttributedString?`
-> name "1f471-1f3fe-2640" -> no image found
`private func fallback(for emoji: EmojiHandler) -> NSAttributedString` 
-> name "2640" -> image found
-> name "1f3fe" -> image found
-> name "1f471" -> image found
`private func replacement(for emoji: EmojiHandler) -> NSAttributedString?`
-> name "1f471-1f3fe.png" -> image found

**Comment by xoudini** [comment]
@ltblueberry0 

All of the above should now work with the version on the master branch, and I pushed the update to Cocoapods as well.

I'll also fix the warnings as soon as possible, so don't panic.

**Comment by xoudini** [comment]
And as for this:
> I am using twemoji image files as they are supplied in the twemoji repo. I did not change the file names.

You'll need to run the renaming script for all twemoji glyphs to work properly, just follow the instructions [here](https://github.com/xoudini/emojica#compatible-image-sets).
